version: 2.1

orbs:
  elixir-orb: fresha/elixir-orb@dev:alpha

workflows:
  version: 2
  ci:
    jobs:
      - elixir-orb/test:
          executor: elixir-orb/elixir-postgres
      - elixir-orb/static-check:
          dialyzer: false
          context: Hex
      - hold-for-dev-publish:
          type: approval
          requires:
            - elixir-orb/test
            - elixir-orb/static-check
          filters:
            branches:
              ignore:
                - master
      - elixir-orb/dev-publish:
          context: Hex
          requires:
            - hold-for-dev-publish
      - elixir-orb/deploy:
          context: Hex
          requires:
            - elixir-orb/test
            - elixir-orb/static-check
          filters:
            branches:
              only:
                - master
